apiVersion: ENC[AES256_GCM,data:NmA=,iv:c+lZ6WVgj/THb/gouWlGZ2yxidT/MxBLLaITArjCc/Y=,tag:f5ucFXd9dGOtfw24fwJQuQ==,type:str]
kind: ENC[AES256_GCM,data:EaQ8GFuN,iv:5CRMBkPnzRZR5WKZ+SoJwuHab4y0m9TTE8ERSacQlPw=,tag:kvN7x44dcc/d9L7Jb8njRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mYuv9PFsb+KO2g==,iv:AyI7hvvM9TGMQc2xNTxOiXIZ+G3cXfk6NwoGk1ywb0Q=,tag:2EjSF918yfZF+zXColUO4w==,type:str]
    namespace: ENC[AES256_GCM,data:pm0i0ds=,iv:yGnV6cSLpzCUS7a6b2Rg3632KZ/OZ+SpdWNsOkNj6rg=,tag:hq6ann0puWCFEV91J9nsrw==,type:str]
type: ENC[AES256_GCM,data:cD4sIbsB,iv:SynzA602MMmx+9Gpw6b4CTBLRbPUszkEIHBNx/erfs0=,tag:loIkRCQ4He58afwnFO8t8w==,type:str]
stringData:
    mysql-root-password: ENC[AES256_GCM,data:YvC9PxBxjnNd/ccRa3oankh4xFHQbpqL47ddnQcvRAFe7eOH3qYaDISfd9g=,iv:SdEnclvsdi6LtEtWKBYmtlzixQbILrw6EnDLn6TYpzg=,tag:Da6iB7lFG5KftXb59VHeeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kga6y9njjc2ykcuj9qapq677mkelkh5x5pxnjf647tk933267c2qjaw694
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeE9ldkhDcjJsMzNIYmxW
            a1Ntc2ExVFAxNjUrYkpqeGVkMU5qWVYxb2ljCmt4MWRLNWRUNXBTamhSdWpZazdo
            azdVVzN3M2F3amVQVFM3bTNaWlo2MHMKLS0tIDc5SDFFUFQzamMxajZ6UDdnbFZt
            TFhLUVljUjQ3NGN1R3FkNTlJMWxUbE0KPjhAVS7c6ACN4s6IqSSdNDG4JpsiepGv
            +WcqfXR/iZLjjN99Z7pvEOzX9PW7dkxow4XB7aUsofrKX6Jp6b8FMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T19:19:44Z"
    mac: ENC[AES256_GCM,data:zWaGRQiQYwN+YmV1S+EShVEk2oiOXJA0g9YZ97823j+URDuXD/FKDok4sLaZ11uvxEvVD78Ly7YLvXkaKJSn0vrj68I0W9jFQpibibWC41+Cg8gwiyw451ceQ9MMyiAXJ52ySN1Jbrc7p2qYDzgUYEjbHb6UykXT+LBIfZenBM8=,iv:49k/UlOywsKES2R9f6rA3/YSTE1rhiOyg2hDuUawNkA=,tag:Gb3gkyk9uRzJIeT9MxdFwQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
