apiVersion: ENC[AES256_GCM,data:mUo=,iv:U+H4O3d2+yOXjgRBsOS/GiufEJ5ixmx9i+GMrKvwNjE=,tag:J7Hn5rTMV8bbw/RASz4y6A==,type:str]
kind: ENC[AES256_GCM,data:kHl5mY8i,iv:bf2Ldq+7lkvwlnLfOFBizOzjpm/hTRp/8tpNGwWkfCQ=,tag:mQY2MNTgqAvDwgb3O18r3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DjL07Je60+vGJaPW,iv:2bhB/+0Ukm1CxJVVbWxgQ7rQqDMio5U+oxCAGAa8Yww=,tag:d0TwLZh7Vsq+LQQaQQSqWw==,type:str]
    namespace: ENC[AES256_GCM,data:qeF+sau/xQJDdpSN,iv:PRyE1O9kLaAVfVizCGHM+B7hpS+vRbtydACcQw6AuyQ=,tag:XuR8cZAXVq7taRnj+k9khg==,type:str]
type: ENC[AES256_GCM,data:s3AmmjEe,iv:PGnNhBTnTBzC7RBYCYAfBKSpV6C579BUG2cqk4/ccFg=,tag:uHC/rUoUZ4wYNtZHqvyBYw==,type:str]
stringData:
    IONOS_PUBLIC_PREFIX: ENC[AES256_GCM,data:ZPndvJ2cAouXkKMW4gxoA6Ts+iQ+2DbShowc+nXkQ6s=,iv:M0l5tkVFGwzmRGhfqUGa5n8d86jXPVqizzO7ei9wgLQ=,tag:nzwCHubhrQxoA7qnbb+vlA==,type:str]
    IONOS_SECRET: ENC[AES256_GCM,data:rMAMHoQGcWcPmMX6DaNWlteLDj9J/zXAnAEKMo/f/lFA2mBgM9CQgiZv0/SDn0Vi6gFm5xPGowsg/mzVBIvcGfeBOGWUQxl5Xh8sbLNPGXsr96Jz1n0=,iv:+Hfo9EMndRkpulI0smQUzPEML/1CuugDbJtRJ/4XEFw=,tag:k0+oMAvYvLZoqiY/ej1cQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kga6y9njjc2ykcuj9qapq677mkelkh5x5pxnjf647tk933267c2qjaw694
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bUJjR2VDeVk0UmUvRDd1
            OVBFblBBT0dSVWNVdjdYRFh0eFdtQXBrbnlzCnpYYk5hMm9KL0JiN0hNUkZ2Nys3
            K2ZWOTdBYVRpZzFreS9IVkN2UE9YemMKLS0tIFpDM3hQQ1JSVTMrZlBncFAyMFBm
            TjZWZTJGQWJHTzdpbVdoWDBZek9qVkEKfylZilB2vxqWOm4CCFxbMdKvbYMomqg6
            gMvBqVqRf3kDs9rPThwVVgx5N/0A/+0AzJrxqfavQeEZJybuN9sEWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-31T19:39:29Z"
    mac: ENC[AES256_GCM,data:gQIACNCToVjK2/47lBxXShPTXzMOP9MS1gRHA3w2Drk2i2u1XUM78ar8Wy6ExuAFiU62Kr61r8jG9jDghNWWjqUOBfbFJJTzTKGaZ1rfcoZONf0Wy5jXLnKvGJZfvy6JFQajY6nfWEaDTPJKdHkmXw2CSUnCmPB3Tbxc3yWdZSQ=,iv:RBX2yQSxZ5UuY7mLIfscadkq7o8MSBGh9cEv7aiSvz0=,tag:8UBBDszuZVoT3K5x9tIggA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
