apiVersion: ENC[AES256_GCM,data:+dM=,iv:mmYuoPxH7guimy2HsxnYdvoxtltFv/IcevOy9djCXys=,tag:v0LnkQuNtJyBTwVcL3/EZA==,type:str]
kind: ENC[AES256_GCM,data:4gjDfxyU,iv:r9yBshq2XtD3OptlmIAJhSQS3x+1P75P/Qzdwyn94VU=,tag:3otWFwVBEKEw1/CdTToRkw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YJEYxDYORHKmDUbaaQ==,iv:G2V/5ORL7gvqJLLwfDPexUJ9PRpEipgy0/Qv8UH4/Zk=,tag:sfAMWlvTbMB9RDH9SMBjPw==,type:str]
    namespace: ENC[AES256_GCM,data:4xwdlOM2g53nvQ==,iv:9lN5+obYJHNWFqUHEgybpUVg4Lgat988SevUVXEBTzo=,tag:h7Aoq8cUvFb/8Q5IYFI2qw==,type:str]
type: ENC[AES256_GCM,data:/KyRBVfT,iv:4vFDzLKUnstsN7Rd7zyUel570bdHRgMNgI7h4mWnDW0=,tag:xDXmLpoEcMBTk/OYfb46hQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:n7NooCM=,iv:KHnnY916nK2K5mtyAsEW6ZkZbSsWkY5QBd0OiW+UbEA=,tag:ZEcF6x99kwGL+BVUZ3r2jg==,type:str]
    admin-password: ENC[AES256_GCM,data:XCZB3A0Pt3A=,iv:Tw5cpgmvTUiS21kYYC9JWRTlKzBqYFXY29eSvPDABTA=,tag:DjOZ3GQmR2OaSXocM4cwWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kga6y9njjc2ykcuj9qapq677mkelkh5x5pxnjf647tk933267c2qjaw694
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMEhsdkpvQmVXQlRDSXdQ
            Qk1TMzg1bGRoTGxDU3ErVUtyRmUwL0lwU0FNCnhlVlkrY3dJQWhhNm84bERmZkVZ
            SjNpYlhEeWFnRGd5ZVlRRjczOWlsUWsKLS0tIDlhVXEwaVpST0UvUFhHV2NyWmJP
            VDZxT21uZjNXUnB3Tnd2WnpRdkxtcGMKv8JLQA78mwUwva3RXuW0NBHvDs6dazWU
            QwXNZ1MdpdnUsSeCNgvddGvO0AoZL9DBT9hJThgz1+RRAJXSa+3X9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T14:31:01Z"
    mac: ENC[AES256_GCM,data:GykMpP0A7brvQoE20gv/CLbKm9V5gDpC1KYkGRjvCMiHGwZqDi6FKfcn0MEHoT83xfEIamwiuuJscAdJojDj8jdryAzOCBOYiYXkOg6lsjmbv3pYj+lnsgIvkKHT0ZOGfuGsCxEFGi7yv0rme1DmqGeeS4KmN2sMp1cz6a7fbQQ=,iv:oElFHq9QAWW6P5+laBA2AOjZjH5+/nIekTTBBiF/bBY=,tag:YP0wvcnjEl2fVgFgvk2arQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
