apiVersion: ENC[AES256_GCM,data:yQg=,iv:xrvoeDQ5M2o7qUHrmoCtvhdBcNlksjpWCalWAa33Rrg=,tag:IxRXAPuFsu1OKqqJgXcWpQ==,type:str]
kind: ENC[AES256_GCM,data:j7wpv+qN,iv:CQ3pHM9Kne0xM7FQecHqK8Gdg784eSSOYYSUWGEW4Qs=,tag:fjMhFVdujBpVCvufP27hzQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MMIl6uieabqUcEJg3A==,iv:6tum9iOC6F5McMghy3LDDMTtimNq53d/EFCKFIHd7Uo=,tag:87mcJ+EYGZUE93miPoLTdg==,type:str]
    namespace: ENC[AES256_GCM,data:oTxU8z63AbcBcg==,iv:sJD12kfKsYTinRc7jBy4gMXv8r8PAuFTqIsphhHtRLw=,tag:+tDvoKvR4WKvtGH88kfWdA==,type:str]
type: ENC[AES256_GCM,data:9g1WqI5o,iv:+zVZ4cnbivwVTXj9+iwjd8l+DofN1VH+XhQXqZKfRxQ=,tag:lI5WIe2KxOBrkBVySgK1gQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:4ElWX38=,iv:KKFnEv/v52h1yh4SH44+Nmp0i2xlM4hot70OvUYOzfw=,tag:oGmBC1kmQDhZeoJyg3jUxQ==,type:str]
    admin-password: ENC[AES256_GCM,data:HeMYdIbUPYg=,iv:bsqQ3MIp+jzEhHtWDDg0fZKAQv29Yl6gmzqYOpvTeUc=,tag:TDxmpd3QdSvtZb8ZJHukDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5dhqw2e4j320s53mzujg9qnptftlhc8gl5xwpt2dc8mz5dhtfjscaaruf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVd2a05POEQvMEx4cjMv
            U0VBYVNpdFBZKzhsSEg5VXBma0hycUo5ZURRCjZ6YzBJZ2xVYVRrU3M0NmU0Q1pT
            TGpvTENUYVduK2tFRkJzS096aFE5azQKLS0tIE1sZzcwZGNBRFpNMnc5WldIeDlZ
            VklrZmUwaC84dXc4OWpUNkVNRzNWOXMKIWW66WrEqbgv9I67xCLLP1O6nAydPS5R
            M57YaCFZtr2sv22E5UZomG3o/Ha/9QSqaV26tfTNNXNpiWDuT6dQ/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T07:30:33Z"
    mac: ENC[AES256_GCM,data:FpJp4JUkhQwu1rdjcPPtZCcVw6aMElF6YthLxuL6QSm8vcm3r+6l7dM75RNcngiBQkXpEkAdtTkRGC4KECkfNOJGeFJUXExwVrdYuMlPSv6wIbz+dXKZiAnhdgexxkjBcXPt3OGJpPYcXGz6gRD2KHk8ha0r4EBmeLMoWHjLpfc=,iv:aKcOJsaZs3ANnBydCuBDqlBU+snvR6qmTzkm32+9rQ0=,tag:JJgfkPywZB385k4N4vrjDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
