apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-config
  namespace: stirling-pdf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-csi-rbd
  resources:
    requests:
      storage: 1Gi
