apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatsappbot-pdfs
  namespace: whatsappbot-golang
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-csi-cephfs
  resources:
    requests:
      storage: 120Gi
