#ENC[AES256_GCM,data:F6aIYVgFqsoKIUhAuu5ag6Q9C5jZTuARbwja7MDxABlUoUL1DThUa+wxD7oTEHuD,iv:hrI+LnFqLjgt6QnDv2aFa6ImA4HPjZmHJ7gHVe8Q84s=,tag:twrSZQA3SbsYbsGD3OZkXQ==,type:comment]
#ENC[AES256_GCM,data:nakIfO5sgPtxu0MJH6oJV6gYqhZ9YFGJ+w8PigS4y2hhdKuWSjHFCbdys3pjzuKS15U=,iv:VCrtpBJGJyay4pZ5CpwQAdHEQ18k9C1Koxa4sK3TbHc=,tag:XMQvTa+I43MdGD9PxAVQew==,type:comment]
#ENC[AES256_GCM,data:SIbMpluLrTPlHH4JWhQaH9bNj9/GVEY+nYKfmExNSjXeXc+Ah3fexQQDZThlq5fdlM0=,iv:qtemNxax+mcFZWmGLx8/FY932Zs8ZD6KaeNTQI9Vbyc=,tag:H9KBL02p3BMuu51GPpsXfA==,type:comment]
#ENC[AES256_GCM,data:f9kqPm9tDx7zyQ6o4Ft0egnJx8VPe/P74ueckGGsr9666k5U6LJ+OvFJ24eAOg==,iv:CAGczw973dcQ60hANaJ9jx6tMEEWptoBIhT/ZrjZdEM=,tag:Cpk4QZj9BP4B4v1aAJUcPg==,type:comment]
#ENC[AES256_GCM,data:hT6zcKcDUGUvbtUVG6e+qQJoaI47VVI2FjreY1i1gFWxv8ZX2pZfstUAa2q4qbq7YjqMQSixyMItDK6m/wl7Yg==,iv:CPiNXiPywEoWIZXqMKKni7taXGm3kKAAOlK6G9/FFrA=,tag:5Cmmmf1oFxwPyu6UezvlmA==,type:comment]
apiVersion: ENC[AES256_GCM,data:zns=,iv:YH4NZ/deq9SAHRF/EbqX2EBZVwMjftdqEnNStokG9IQ=,tag:p2G0F52RjIUIbTNhAbqJwQ==,type:str]
kind: ENC[AES256_GCM,data:OUhcfkjY,iv:G2j9PghOxUAVdgCKB6jKH2o6SidiIbBkd4mQU9EgF1M=,tag:AMGPak8U8RL2LINjl/N2WA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jELdMrthGDQx5z1l0B9rmtnx,iv:vmvXliLk3ovvN3AbLn9AQo76HwydhS32uCKN9egx9QE=,tag:9BqIlTRgLOGGLyzScdIiGg==,type:str]
    namespace: ENC[AES256_GCM,data:+mqv0HL6AP3jPFQIu9O75gcs,iv:P0wYkd96TqtAzRS5ylH2J3Vca9eA/v26I29D0T0KAsE=,tag:UJ6AoiV4uBCmDyINwJXIvw==,type:str]
type: ENC[AES256_GCM,data:JHFEybyj,iv:vVVUdNW6TaJUjBuUelSmYP2mXXrmJZYFkCM1lhNU9hM=,tag:xzn2DVadtM0YOjFLu0heIQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:LUMd3PrcDBWxa8kB76YcKvQy,iv:yWrVK17jWXfl9ucJKvaNRlQq42n7SQ92t9MQTKEQ9RU=,tag:I8yFGXcVdjCFM+eQ8Zoh8w==,type:comment]
    BOT_NUMBER: ENC[AES256_GCM,data:ZUxJ4061Gq36zl+QhQ==,iv:O0pPvuX3Xfjmh4ZNgQ07fa0tkxqgAbK3VDY2yzmCtcY=,tag:zGsNh5ynMKjAT3ij3ljK2Q==,type:str]
    BOT_NOTIFICATION_JID: ENC[AES256_GCM,data:ki8zswW+AAuLca1xR1KQuw==,iv:vDaaHXaP/j1hKs8EXhLzc9kNZu6gPT2n4+aFyUN1HVU=,tag:flbIqOqA/8Sx6vyyD0V4FA==,type:str]
    #ENC[AES256_GCM,data:uQQUtsT7O92G4YOrOEelk5GtPtqS0nOjGDIOsSuJSn5C0LNgVMzyTFmF,iv:pBO6SoT7cu9ct2L9JItpBefmyXPoc9G7D0hLBszMIrw=,tag:53/kG1RyLc5hadWlqatUvg==,type:comment]
    BOT_MENTIONED_NUMBER: ""
    #ENC[AES256_GCM,data:ohy/R+A978NHZ9tqD+yqf2BzpgfKXswbveuJJdBDkQ==,iv:4RDoBCnl06mKzeKUd2yNtWlxvQyvKfPa74DtHpobcLQ=,tag:JR5vjCHCDRj1I6gC5L8AtA==,type:comment]
    BOT_TROLL_NUMBERS: ""
    #ENC[AES256_GCM,data:aW0ASiB/32XYz/3ItXY5pmzxKiGgesICOAQl5hGtxOaOKsozGUsKMH4AskocPoTQ61DKDovjzA==,iv:4xlULFEFlGciZKNbh5C0IP6Kt2qoDTmnkqMpeAGtxW0=,tag:7MD/anogtowGIKGhMzZ7iw==,type:comment]
    BOT_PAIR_PHONE: ""
    #ENC[AES256_GCM,data:+WjVXQYQi1sp0QCpQE+xcLBPRrZX+wQ0YYb+JBXKGogqdz/Xp+8laWlAZpMkqYnM/LhsIU07pWGdDvOBtZPxLJBB,iv:kpqvB07YTDMx6lHfw+7nuA7IiaRv+HY31oDLmJL/gig=,tag:0gLm2Bb5r8eJCBWw9buixA==,type:comment]
    #ENC[AES256_GCM,data:hPepQIBFi6ggzHEelh8THKs0yMfJTvWUAgI6dVCMsS2oB0RX7/VpEqDMhiMkiv64gB20p/JEl2bZ2ZSvCTUwLREfRYKyaXivH7KqUT7H7HuRNcrHDKmL,iv:r7XFMjxpE5EEsyYbvkHglmvsx8BzWq2Frdoss3WkqMk=,tag:Fc80PsLcJgMeI2Bl0hu+Lg==,type:comment]
    DB_DSN: ENC[AES256_GCM,data:UqQiXN5aKeqNsJpV7VNMbzOTTfCnLgNnTwoL7EvwVd+EOogrCidPHj5mu+Lajd4EglhX4gzNVIAAweS2hlKPJa6FHEAXaZE3K5vMvXf1Bf23CjCUgGxMieCn2sZOYxqI1lLTZSlkaxp18nP3vGG6rSLU,iv:zb6M7VjnY+m31ElUsRF1vXDk5pGKW5695Nf+yhCHTkM=,tag:naJ2ZfX86NdKvWgubOt/1A==,type:str]
    DB_AUTO_CREATE: ENC[AES256_GCM,data:fnokHA==,iv:PSbmSeFok4C/AOADkOQozoY1yPaQ0d8rC5ZT46xwggs=,tag:sFSxPgZpxV3y+ldLbciiBA==,type:str]
    #ENC[AES256_GCM,data:uPTFNc1rBkuWTrrslys=,iv:UHIMWZQp0julND5pPHex1YzrJaLTea4hMypL6gh6ciw=,tag:R6MfS9mGQLZFX+mPTpW0mA==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:cOspv9IBD0Fc/Yw8TcsQJqZyeasQMNXqR5ZOzgK20Gu3L+qq03KLB3YRCf/G9kuXbi5i,iv:7BwKUjDHf/NKJh6raxsktkhZ723sitRXW4n/SosQz10=,tag:JYDBAgW8DH+1BQylUCU4iA==,type:str]
    WEATHER_API_KEY: ENC[AES256_GCM,data:cNJRMvyfWkeuqrdyVggf6R83UBlLdKJXCqANUuUFomw=,iv:XClLHDmySg0CsjY5bBSNVr8arF9sO1zZkDpVGPEw8R0=,tag:q+Q7Y8UNz8U4BYz2lNKQfg==,type:str]
    STABILITY_API_KEY: ENC[AES256_GCM,data:i9m+mfCo26+1mtRHyi8ruh8Puy+wzR5XvyhtlR/7cKsp+LDj2HJDXFOvg9Q2Ozd/8YPN,iv:n4scDJmoiSYQzkFc9mqtzxPJS5rnP0HP0RrLJDYIzf0=,tag:Y8H4unY2cCAnj5ZpMo3HCA==,type:str]
    ESIOS_API_KEY: ENC[AES256_GCM,data:0ky3KxRW1BdUo/OHMPwDF3J/TrBDlqCqNZPRuFcs17qo+nda6M8VM6fc/UmBNweDjjGA5LIt2Uunbeq2fthvYw==,iv:7rOQrT+dSpJRgR5l+NNnX3bN1VVYdmMGvi+POfFE4kA=,tag:XjYsqZc5oDrl/7rdrEZgJg==,type:str]
    #ENC[AES256_GCM,data:GzVmUxeG1ud8YNoVX1ZaX4QJJvJNoj7L2TbW3VoJ1A==,iv:2Tl8Yq2r1MpE/+B3QWY0LrJ1nYRz2c7TphNluXjzdqw=,tag:rE5BFYU/yhkNE71IVTkMcA==,type:comment]
    #ENC[AES256_GCM,data:r+62nTJhCp2ZVWxqrjFux5syYH7UX16s7mipUXaMiCnLDNXeNg==,iv:86CpP5jbARo57OfdVHdJgcqCcT2qUDB6UmguPCymhxI=,tag:YBgz9niqaAowCrCnhppXeQ==,type:comment]
    PDF_CHANNEL_JID: ""
    #ENC[AES256_GCM,data:XhLPSmOFqlhCB5NNm1bi3QUyevXAKnpb5D6W,iv:FjBN9T/r6rf+jfaSqckq6QJZUjtcLx3R4aMtv8Qcx/8=,tag:bzzblwNSbRwhF4zjCwKihQ==,type:comment]
    jwt-public.pem: ENC[AES256_GCM,data:v1aeK/ziJHCgSjQHmkM48OhdIF2lc0kIG+naoQv+2ahL9W+PfYkqOQSS2OsWkHsfUCk9oj0niRMyb7neCUeI,iv:p2vqHh8dipE5dl3wYhoLlBk8/SUVVHGDK/RII6eQiSo=,tag:r211Z6zCR78ehJDCgUppDg==,type:str]
    jwt-private.pem: ENC[AES256_GCM,data:ZWwKdfyx8V2hwsb85XuJa5l7AmbqBwQayVd19ytz02fbuoxTi1TqQaC4TRhxQuhBwIQYpbtYvs3vvOAff9wvu9zvPw0TikZm2w==,iv:LJJaK3n3CQCOWj4WJy7jCKsx3QL0/UiPk/OhRzagAdQ=,tag:KJWL0+7JxftUb64oYGjPyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kga6y9njjc2ykcuj9qapq677mkelkh5x5pxnjf647tk933267c2qjaw694
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVHJJVEZuK2YyTTVIZWQ4
            ZUc0TWp6c1E0QlB2bEtkVEhueVp2aU9FMENFClVqekd2bE1EU0pJcHl3dWNTblZv
            K1U2NC9TUzdrT1VQRi9BbFd0SlRpY1EKLS0tIGZHOEplVVRvOW9ETndGbXNEbFZk
            VTBOaWZFMGZnbmNmQ2EvZnpvZWpEMjgKnV4BEjLZewltdhkq0dX9QwojOxw+lAJ1
            l8UQmvhWPvEYCld5768eFKBW1I2BkZX+0Y+QoTTBk4Zx2xx4RoYx0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:18:38Z"
    mac: ENC[AES256_GCM,data:MPbj499izBs5/eNpoLd1oVaWxPvLZGBX0hfTWpOtJ8JW2SVAWUIKiuI3g9/Ou1AX53sU+8JhDN0EsVaeHTzlqNItj5TubNITOVuM/UyItDOGkPgavAgx9AKp/VLBjNionBn7IT2rGnERY/JrSljM6PMu60Xlr10JY7sWlui9Vms=,iv:dHoI0BNsHcSeKcJd0S5bF3RD7QH1Wckg6Dfn2WkPoho=,tag:CcxQcOG+U9JM06Bhd/JgyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
