apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notifierwhatsapp
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - image-repository.yaml
  - image-policy.yaml
  - image-update-automation.yaml
