apiVersion: v1
kind: Service
metadata:
  name: notifierwhatsapp
  namespace: notifierwhatsapp
spec:
  type: LoadBalancer
  loadBalancerIP: 172.26.20.33
  selector:
    app: notifierwhatsapp
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
