---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notifierwhatsapp
  namespace: notifierwhatsapp
  labels:
    app: notifierwhatsapp
spec:
  selector:
    matchLabels:
      app: notifierwhatsapp
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
