apiVersion: ENC[AES256_GCM,data:G5k=,iv:uXw+2xEm399sVfJLpcL02/RK1OEXtemmj9YE7icT4MQ=,tag:MCPPOSIhY69iU3tMj9/0wA==,type:str]
kind: ENC[AES256_GCM,data:Q9aMMvzT,iv:cP68cJAtPp03ccgxlB/K8vC+/R4jm9RuesypzDzqieg=,tag:nhY7xH9+CHrpzJCzbixE4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:y8q6j0UYzITfV4///Bs/,iv:xzaACld5cURh0lG0IrKRvipa5Sk/cQOL7KKUQT3elsQ=,tag:HrGmGFI1Z8+070esgF5kyA==,type:str]
    namespace: ENC[AES256_GCM,data:WRatmHpVD8+tBchF,iv:SONAasd68mAdXNRc3xf6exj4sBi9Hxv3NFhxDv1H/Os=,tag:HxvQnC+RtRFLnhBSs3+42g==,type:str]
type: ENC[AES256_GCM,data:18BWvW/b,iv:cjEpm57T7wjXmq/lZ3h8jkPB5efYnfg3jRq1rZ+XJuw=,tag:xnCZo/mPrdWWSyO9gdXNwg==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HHZFw4oqHb4aN73AVsUt,iv:HijkB+jf4ZTzMYWIcIq9wB1OZJF/6ZhmBDnqxuP9ECg=,tag:eXDaNdcszho0YwIdRDXHtA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:+6xSWACNLHU=,iv:EG3FVyJQYJk/Mr768rXsnHUxdnoJWsz3SiCVSlT9W7g=,tag:E/3A3aK0SZaw50jw4WOsMQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Lfzl3C+U,iv:duZ2tCJ35Np4WzuG0rGJ8OtBc5ngJA551Ol/6wroe/k=,tag:8gVbq7GvfwgKCvY4pTFiVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5dhqw2e4j320s53mzujg9qnptftlhc8gl5xwpt2dc8mz5dhtfjscaaruf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQm96WjJWdDlySG5yY0hP
            eDJOenZuUEZOTTRGT3RPeUVhbVZFMEZsbmlRClRuOVhwUHdOVzZOZDdmNnc4S3NC
            bFZMRVdrcUlhTGJIK2xMWS9uMzAxUmMKLS0tIFExQUdja3BiazBYWXlqcUY1TW1D
            aDBpeExXWnNzSEJhSEFYOWtoRzhJZWMKbkRakX522w/jVfOu70rb0E3dYbU5CcUt
            rOaOItrwzaHGcF+a0Tmx8xr2zOvn/MzWE47X9b5qmcmgcu/O3VjIsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T09:09:35Z"
    mac: ENC[AES256_GCM,data:7D0TUUeGLjimO4f2z5CEL3W/Sx3438v//xGOTzulJlb86PwkeRtaa0pNyW+huoBF0MtoU9/dkpClfOH0e204lAWTf6l05fCR5nBUY4zL2uefPOwUe77MEfXu2vlHeCK/rdR7bSqcFaK5Ejg/q6qQUYfwJLC2mwzg8YLGXwrwlTI=,iv:ffRRU0BRbILSS707gD5agCAXcLL2ruQVAV6634Jr2Q0=,tag:9boYc4ynfts05EaFY0LFCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
