apiVersion: ENC[AES256_GCM,data:cX4=,iv:wKqtCrWcuw+CuCt++x1NHVWMUzqnQiU5sSYR+1K17O8=,tag:wIez0/Te8zFXLTlSTCyJSg==,type:str]
kind: ENC[AES256_GCM,data:3ddFn2so,iv:zlIsEctooBj1xSP14oHS6LgB/Jd3g7Fsm30XwLsvX2g=,tag:WjSb/5FHreT5PGqcBKWUCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ga8jMcFDOBGlxQHd,iv:XTnvzeXKDf/ozraqWx/W4tVlnnOktJTwj+u+GcKskoM=,tag:sn1qUj6XsY3Ize81JxHgXA==,type:str]
    namespace: ENC[AES256_GCM,data:gvHzpUUQ,iv:F47InWhkEESv15JOAZ687VYTFJ3e2Saue1taeK7I4M0=,tag:higcTqkwibjgOy84HwhHPA==,type:str]
type: ENC[AES256_GCM,data:fjohX8gA,iv:lHFfpRGnX2guYbWgeYdGk10U1GWXu/gdy+qd1KhigIo=,tag:IffPufSchrZjfhzZmmE9Gw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:idvSV3cylqs=,iv:eExkpY1NeU2s6kdDNAYwlI4uAvu2l9wkmoOHhJKD4vE=,tag:55Ckp8a7Qtro5U0ZtH8wTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kga6y9njjc2ykcuj9qapq677mkelkh5x5pxnjf647tk933267c2qjaw694
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OWVFSXVYUlF4dGdKL0lE
            THI0ci9keXVqdkN2VW1wdXd3bmdGdkJtYVQ4CmRYdUEyU0JZcWhNR3FONmZyaFJv
            eTVONUZqZDRMcGtxR1BrOFZlNTViTU0KLS0tIERwMm1yVXh6QkZYOGpMb2dmVHBR
            Rzh1cDRvUDdKTjJCUXFqNUhGbnplYWcKrIAKu1SpCSRzuQd6Zy7YPmZSXRKpl9wF
            3TR9KFzwbvfmLqScol8SAIy2V21FenpFjluGX/ZXdLtEZzknRoqSFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T16:10:54Z"
    mac: ENC[AES256_GCM,data:Wtk4uH13rVfuWGUZ0IskanbiW1CDX8ZJsCjA8Ud1lU7dpyNcoSvZzl+zeqRzbHzi9qVuMx17xI8BIbS6OE4RRAt3vXPXNbJFcDkdEqAdEWCL4PdO6gS9nosVniIziYfengdc1e+rFHUsgnYxemQ0H5mRRD4M5uEKf2X1Iyti3aM=,iv:6bt1uuvpiCblFELByCaQfuVeVUscjHzXzuzJiLbXUp8=,tag:Gojhqw/+T+gGpc9aOxGCDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
