---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster
  prune: false
  sourceRef:
    kind: GitRepository
    name: k8s-homelab-gitops
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
